/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.services;

import javax.annotation.Nonnull;
import javax.inject.Named;
import vdm.namespaces.zscpaidasrv.FornitoreByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.FornitoreFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_MNGByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_MNGFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_PERSByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_PERSFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_SIAByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.HR_SIAFluentHelper;
import vdm.namespaces.zscpaidasrv.HrorgByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.HrorgFluentHelper;
import vdm.namespaces.zscpaidasrv.OdmByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.OdmFluentHelper;
import vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERSByKeyFluentHelper;
import vdm.namespaces.zscpaidasrv.batch.DefaultZSCPAIDASRVServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>ZSCP_AIDA_SRV</td></tr></table>
 * 
 */
@Named("vdm.services.DefaultZSCPAIDASRVService")
public class DefaultZSCPAIDASRVService
    implements ZSCPAIDASRVService
{

    @Nonnull
    private final String servicePath;

    /**
     * Creates a service using {@link ZSCPAIDASRVService#DEFAULT_SERVICE_PATH} to send the requests.
     * 
     */
    public DefaultZSCPAIDASRVService() {
        servicePath = ZSCPAIDASRVService.DEFAULT_SERVICE_PATH;
    }

    /**
     * Creates a service using the provided service path to send the requests.
     * <p>
     * Used by the fluent {@link #withServicePath(String)} method.
     * 
     */
    private DefaultZSCPAIDASRVService(
        @Nonnull
        final String servicePath) {
        this.servicePath = servicePath;
    }

    @Override
    @Nonnull
    public DefaultZSCPAIDASRVService withServicePath(
        @Nonnull
        final String servicePath) {
        return new DefaultZSCPAIDASRVService(servicePath);
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Override
    @Nonnull
    public DefaultZSCPAIDASRVServiceBatch batch() {
        return new DefaultZSCPAIDASRVServiceBatch(this);
    }

    @Override
    @Nonnull
    public FornitoreFluentHelper getAllFornitore() {
        return new FornitoreFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public FornitoreByKeyFluentHelper getFornitoreByKey(final String lifnr) {
        return new FornitoreByKeyFluentHelper(servicePath, lifnr);
    }

    @Override
    @Nonnull
    public OdmFluentHelper getAllOdm() {
        return new OdmFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public OdmByKeyFluentHelper getOdmByKey(final String inOrder, final String ouOrderid) {
        return new OdmByKeyFluentHelper(servicePath, inOrder, ouOrderid);
    }

    @Override
    @Nonnull
    public HrorgFluentHelper getAllHrorg() {
        return new HrorgFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public HrorgByKeyFluentHelper getHrorgByKey(final String usrid) {
        return new HrorgByKeyFluentHelper(servicePath, usrid);
    }

    @Override
    @Nonnull
    public HR_PERSFluentHelper getAllHR_PERS() {
        return new HR_PERSFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public HR_PERSByKeyFluentHelper getHR_PERSByKey(final String usrid) {
        return new HR_PERSByKeyFluentHelper(servicePath, usrid);
    }

    @Override
    @Nonnull
    public HR_SIAFluentHelper getAllHR_SIA() {
        return new HR_SIAFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public HR_SIAByKeyFluentHelper getHR_SIAByKey(final String mandt) {
        return new HR_SIAByKeyFluentHelper(servicePath, mandt);
    }

    @Override
    @Nonnull
    public HR_MNGFluentHelper getAllHR_MNG() {
        return new HR_MNGFluentHelper(servicePath);
    }

    @Override
    @Nonnull
    public HR_MNGByKeyFluentHelper getHR_MNGByKey(final String uosap) {
        return new HR_MNGByKeyFluentHelper(servicePath, uosap);
    }

    @Override
    @Nonnull
    public ZAIDA_HR_PERSByKeyFluentHelper getZAIDA_HR_PERSByKey(final String iUsrid) {
        return new ZAIDA_HR_PERSByKeyFluentHelper(servicePath, iUsrid);
    }

}
