/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpaidasrv.Fornitore;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpaidasrv.Fornitore Fornitore}. This interface is used by {@link vdm.namespaces.zscpaidasrv.field.FornitoreField FornitoreField} and {@link vdm.namespaces.zscpaidasrv.link.FornitoreLink FornitoreLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpaidasrv.Fornitore#LIFNR LIFNR}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Fornitore#DESCR DESCR}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Fornitore#PIVA PIVA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Fornitore#ZZVMDCUI ZZVMDCUI}</li>
 * </ul>
 * 
 */
public interface FornitoreSelectable
    extends EntitySelectable<Fornitore>
{


}
