/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpaidasrv.HR_MNG;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpaidasrv.HR_MNG HR_MNG}. This interface is used by {@link vdm.namespaces.zscpaidasrv.field.HR_MNGField HR_MNGField} and {@link vdm.namespaces.zscpaidasrv.link.HR_MNGLink HR_MNGLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#I_LEVEL I_LEVEL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#I_UOSAP I_UOSAP}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#MANDT MANDT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#UOSAP UOSAP}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#LIVELLO LIVELLO}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#USRID USRID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.HR_MNG#MAIL MAIL}</li>
 * </ul>
 * 
 */
public interface HR_MNGSelectable
    extends EntitySelectable<HR_MNG>
{


}
