/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpaidasrv.Hrorg;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpaidasrv.Hrorg Hrorg}. This interface is used by {@link vdm.namespaces.zscpaidasrv.field.HrorgField HrorgField} and {@link vdm.namespaces.zscpaidasrv.link.HrorgLink HrorgLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#I_USRID I_USRID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#USRID USRID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERNR PERNR}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#STAT2 STAT2}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#BUKRS BUKRS}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERSA PERSA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#BTRTL BTRTL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#ORGEH ORGEH}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERSG PERSG}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERSK PERSK}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PLANS PLANS}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#STELL STELL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#ENAME ENAME}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#MAIL MAIL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#CENEL CENEL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#BUSLINE BUSLINE}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERIMETER PERIMETER}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#ORGEH_TEXT ORGEH_TEXT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#BTRTL_DESC BTRTL_DESC}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#BUSLINE_TEXT BUSLINE_TEXT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#PERIM_TEXT PERIM_TEXT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#DPERSG DPERSG}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#DPERSK DPERSK}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#DPLANS DPLANS}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Hrorg#DSTELL DSTELL}</li>
 * </ul>
 * 
 */
public interface HrorgSelectable
    extends EntitySelectable<Hrorg>
{


}
