/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpaidasrv.Odm;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpaidasrv.Odm Odm}. This interface is used by {@link vdm.namespaces.zscpaidasrv.field.OdmField OdmField} and {@link vdm.namespaces.zscpaidasrv.link.OdmLink OdmLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#IN_ORDER IN_ORDER}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_ORDERID OU_ORDERID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_ORDERID_D OU_ORDERID_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_SEDE_TECNICA OU_SEDE_TECNICA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_SEDE_TECNICA_D OU_SEDE_TECNICA_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_EQUIPMENT OU_EQUIPMENT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_EQUIPMENT_D OU_EQUIPMENT_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_ASSEMBLAGGIO OU_ASSEMBLAGGIO}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_ASSEMBLAGGIO_D OU_ASSEMBLAGGIO_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_SUPERIOR_ORDERID OU_SUPERIOR_ORDERID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_CFT OU_CFT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_CFT_D OU_CFT_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_REGIONE OU_REGIONE}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_REGIONE_D OU_REGIONE_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_TIPOLOGIA OU_TIPOLOGIA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_TIPOLOGIA_D OU_TIPOLOGIA_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_PARTE OU_PARTE}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_PARTE_D OU_PARTE_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_SEZIONE OU_SEZIONE}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_SEZIONE_D OU_SEZIONE_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_CDL_RESP OU_CDL_RESP}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OU_CDL_RESP_D OU_CDL_RESP_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#OPERAZIONE OPERAZIONE}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#ATTIVITA ATTIVITA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#ATTIVITA_D ATTIVITA_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#MATL_GROUP MATL_GROUP}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#MATL_GROUP_D MATL_GROUP_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#AGREEMENT AGREEMENT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#AGMT_ITEM AGMT_ITEM}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#IMPRESA_ESEC IMPRESA_ESEC}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#IMPRESA_ESEC_D IMPRESA_ESEC_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#IMPRESA_AF IMPRESA_AF}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#IMPRESA_AF_D IMPRESA_AF_D}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#LCL LCL}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#LCL_ITEM LCL_ITEM}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.Odm#ORDERID_TESTATA ORDERID_TESTATA}</li>
 * </ul>
 * 
 */
public interface OdmSelectable
    extends EntitySelectable<Odm>
{


}
