/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.selectable;

import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.EntitySelectable;
import vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS;


/**
 * Interface to enable OData entity selectors for {@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS ZAIDA_HR_PERS}. This interface is used by {@link vdm.namespaces.zscpaidasrv.field.ZAIDA_HR_PERSField ZAIDA_HR_PERSField} and {@link vdm.namespaces.zscpaidasrv.link.ZAIDA_HR_PERSLink ZAIDA_HR_PERSLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#I_USRID I_USRID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#I_NAME I_NAME}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#MANDT MANDT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#USRID USRID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#PERNR PERNR}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#NACHN NACHN}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#VORNA VORNA}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#GBDAT GBDAT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#GBORT GBORT}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#GESCH GESCH}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#PERID PERID}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#NATIO NATIO}</li>
 * <li>{@link vdm.namespaces.zscpaidasrv.ZAIDA_HR_PERS#I_LASTNAME I_LASTNAME}</li>
 * </ul>
 * 
 */
public interface ZAIDA_HR_PERSSelectable
    extends EntitySelectable<ZAIDA_HR_PERS>
{


}
