/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.FluentHelperByKey;
import vdm.namespaces.zscpaidasrv.selectable.HR_MNGSelectable;


/**
 * Fluent helper to fetch a single {@link vdm.namespaces.zscpaidasrv.HR_MNG HR_MNG} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class HR_MNGByKeyFluentHelper
    extends FluentHelperByKey<HR_MNGByKeyFluentHelper, HR_MNG, HR_MNGSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link vdm.namespaces.zscpaidasrv.HR_MNG HR_MNG} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code HR_MNG}
     * @param uosap
     *     
     */
    public HR_MNGByKeyFluentHelper(
        @Nonnull
        final String servicePath, final String uosap) {
        super(servicePath);
        this.key.put("Uosap", uosap);
    }

    @Override
    @Nonnull
    protected Class<HR_MNG> getEntityClass() {
        return HR_MNG.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
