/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.s4hana.connectivity.ErpConfigContext;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import vdm.namespaces.zscpaidasrv.field.HR_SIAField;
import vdm.namespaces.zscpaidasrv.selectable.HR_SIASelectable;
import vdm.services.ZSCPAIDASRVService;


/**
 * <p>Original entity name from the Odata EDM: <b>HR_SIA</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class HR_SIA
    extends VdmEntity<HR_SIA>
{

    /**
     * Selector for all available fields of HR_SIA.
     * 
     */
    public final static HR_SIASelectable ALL_FIELDS = new HR_SIASelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ILevel</b></p>
     * 
     * @return
     *     The iLevel contained in this entity.
     */
    @SerializedName("ILevel")
    @JsonProperty("ILevel")
    @Nullable
    @ODataField(odataName = "ILevel")
    private String iLevel;
    /**
     * Use with available fluent helpers to apply the <b>ILevel</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> I_LEVEL = new HR_SIAField<String>("ILevel");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>IUosap</b></p>
     * 
     * @return
     *     The iUosap contained in this entity.
     */
    @SerializedName("IUosap")
    @JsonProperty("IUosap")
    @Nullable
    @ODataField(odataName = "IUosap")
    private String iUosap;
    /**
     * Use with available fluent helpers to apply the <b>IUosap</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> I_UOSAP = new HR_SIAField<String>("IUosap");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Mandt</b></p>
     * 
     * @return
     *     The mandt contained in this entity.
     */
    @Key
    @SerializedName("Mandt")
    @JsonProperty("Mandt")
    @Nullable
    @ODataField(odataName = "Mandt")
    private String mandt;
    /**
     * Use with available fluent helpers to apply the <b>Mandt</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> MANDT = new HR_SIAField<String>("Mandt");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Uosap</b></p>
     * 
     * @return
     *     The uosap contained in this entity.
     */
    @SerializedName("Uosap")
    @JsonProperty("Uosap")
    @Nullable
    @ODataField(odataName = "Uosap")
    private String uosap;
    /**
     * Use with available fluent helpers to apply the <b>Uosap</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> UOSAP = new HR_SIAField<String>("Uosap");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Livello</b></p>
     * 
     * @return
     *     The livello contained in this entity.
     */
    @SerializedName("Livello")
    @JsonProperty("Livello")
    @Nullable
    @ODataField(odataName = "Livello")
    private String livello;
    /**
     * Use with available fluent helpers to apply the <b>Livello</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> LIVELLO = new HR_SIAField<String>("Livello");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>UosapHse</b></p>
     * 
     * @return
     *     The uosapHse contained in this entity.
     */
    @SerializedName("UosapHse")
    @JsonProperty("UosapHse")
    @Nullable
    @ODataField(odataName = "UosapHse")
    private String uosapHse;
    /**
     * Use with available fluent helpers to apply the <b>UosapHse</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> UOSAP_HSE = new HR_SIAField<String>("UosapHse");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>Short</b></p>
     * 
     * @return
     *     The shortProperty contained in this entity.
     */
    @SerializedName("Short")
    @JsonProperty("Short")
    @Nullable
    @ODataField(odataName = "Short")
    private String shortProperty;
    /**
     * Use with available fluent helpers to apply the <b>Short</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> SHORT_PROPERTY = new HR_SIAField<String>("Short");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Usrid</b></p>
     * 
     * @return
     *     The usrid contained in this entity.
     */
    @SerializedName("Usrid")
    @JsonProperty("Usrid")
    @Nullable
    @ODataField(odataName = "Usrid")
    private String usrid;
    /**
     * Use with available fluent helpers to apply the <b>Usrid</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> USRID = new HR_SIAField<String>("Usrid");
    /**
     * Constraints: Not nullable, Maximum length: 250 <p>Original property name from the Odata EDM: <b>UsridLong</b></p>
     * 
     * @return
     *     The usridLong contained in this entity.
     */
    @SerializedName("UsridLong")
    @JsonProperty("UsridLong")
    @Nullable
    @ODataField(odataName = "UsridLong")
    private String usridLong;
    /**
     * Use with available fluent helpers to apply the <b>UsridLong</b> field to query operations.
     * 
     */
    public final static HR_SIAField<String> USRID_LONG = new HR_SIAField<String>("UsridLong");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<HR_SIA> getType() {
        return HR_SIA.class;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>ILevel</b></p>
     * 
     * @param iLevel
     *     The iLevel to set.
     */
    public void setILevel(
        @Nullable
        final String iLevel) {
        rememberChangedField("ILevel", this.iLevel);
        this.iLevel = iLevel;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>IUosap</b></p>
     * 
     * @param iUosap
     *     The iUosap to set.
     */
    public void setIUosap(
        @Nullable
        final String iUosap) {
        rememberChangedField("IUosap", this.iUosap);
        this.iUosap = iUosap;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>Mandt</b></p>
     * 
     * @param mandt
     *     The mandt to set.
     */
    public void setMandt(
        @Nullable
        final String mandt) {
        rememberChangedField("Mandt", this.mandt);
        this.mandt = mandt;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Uosap</b></p>
     * 
     * @param uosap
     *     The uosap to set.
     */
    public void setUosap(
        @Nullable
        final String uosap) {
        rememberChangedField("Uosap", this.uosap);
        this.uosap = uosap;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Livello</b></p>
     * 
     * @param livello
     *     The livello to set.
     */
    public void setLivello(
        @Nullable
        final String livello) {
        rememberChangedField("Livello", this.livello);
        this.livello = livello;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>UosapHse</b></p>
     * 
     * @param uosapHse
     *     The uosapHse to set.
     */
    public void setUosapHse(
        @Nullable
        final String uosapHse) {
        rememberChangedField("UosapHse", this.uosapHse);
        this.uosapHse = uosapHse;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>Short</b></p>
     * 
     * @param shortProperty
     *     The shortProperty to set.
     */
    public void setShortProperty(
        @Nullable
        final String shortProperty) {
        rememberChangedField("Short", this.shortProperty);
        this.shortProperty = shortProperty;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Usrid</b></p>
     * 
     * @param usrid
     *     The usrid to set.
     */
    public void setUsrid(
        @Nullable
        final String usrid) {
        rememberChangedField("Usrid", this.usrid);
        this.usrid = usrid;
    }

    /**
     * Constraints: Not nullable, Maximum length: 250 <p>Original property name from the Odata EDM: <b>UsridLong</b></p>
     * 
     * @param usridLong
     *     The usridLong to set.
     */
    public void setUsridLong(
        @Nullable
        final String usridLong) {
        rememberChangedField("UsridLong", this.usridLong);
        this.usridLong = usridLong;
    }

    @Override
    protected String getEntityCollection() {
        return "HR_SIASet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("Mandt", getMandt());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("ILevel", getILevel());
        values.put("IUosap", getIUosap());
        values.put("Mandt", getMandt());
        values.put("Uosap", getUosap());
        values.put("Livello", getLivello());
        values.put("UosapHse", getUosapHse());
        values.put("Short", getShortProperty());
        values.put("Usrid", getUsrid());
        values.put("UsridLong", getUsridLong());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("ILevel")) {
                final Object value = values.remove("ILevel");
                if ((value == null)||(!value.equals(getILevel()))) {
                    setILevel(((String) value));
                }
            }
            if (values.containsKey("IUosap")) {
                final Object value = values.remove("IUosap");
                if ((value == null)||(!value.equals(getIUosap()))) {
                    setIUosap(((String) value));
                }
            }
            if (values.containsKey("Mandt")) {
                final Object value = values.remove("Mandt");
                if ((value == null)||(!value.equals(getMandt()))) {
                    setMandt(((String) value));
                }
            }
            if (values.containsKey("Uosap")) {
                final Object value = values.remove("Uosap");
                if ((value == null)||(!value.equals(getUosap()))) {
                    setUosap(((String) value));
                }
            }
            if (values.containsKey("Livello")) {
                final Object value = values.remove("Livello");
                if ((value == null)||(!value.equals(getLivello()))) {
                    setLivello(((String) value));
                }
            }
            if (values.containsKey("UosapHse")) {
                final Object value = values.remove("UosapHse");
                if ((value == null)||(!value.equals(getUosapHse()))) {
                    setUosapHse(((String) value));
                }
            }
            if (values.containsKey("Short")) {
                final Object value = values.remove("Short");
                if ((value == null)||(!value.equals(getShortProperty()))) {
                    setShortProperty(((String) value));
                }
            }
            if (values.containsKey("Usrid")) {
                final Object value = values.remove("Usrid");
                if ((value == null)||(!value.equals(getUsrid()))) {
                    setUsrid(((String) value));
                }
            }
            if (values.containsKey("UsridLong")) {
                final Object value = values.remove("UsridLong");
                if ((value == null)||(!value.equals(getUsridLong()))) {
                    setUsridLong(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >HR_SIAField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new HR_SIAField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >HR_SIAField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new HR_SIAField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public ErpConfigContext getErpConfigContext() {
        return super.getErpConfigContext();
    }

    /**
     * 
     * @deprecated
     *     Use {@link #attachToService(String, ErpConfigContext)} instead.
     */
    @Override
    @Deprecated
    public void setErpConfigContext(
        @Nullable
        final ErpConfigContext erpConfigContext) {
        super.setErpConfigContext(erpConfigContext);
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nullable
        final ErpConfigContext configContext) {
        super.attachToService(servicePath, configContext);
    }

    @Override
    protected String getDefaultServicePath() {
        return ZSCPAIDASRVService.DEFAULT_SERVICE_PATH;
    }

}
