/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.s4hana.connectivity.ErpConfigContext;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import vdm.namespaces.zscpaidasrv.field.HrorgField;
import vdm.namespaces.zscpaidasrv.selectable.HrorgSelectable;
import vdm.services.ZSCPAIDASRVService;


/**
 * <p>Original entity name from the Odata EDM: <b>Hrorg</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class Hrorg
    extends VdmEntity<Hrorg>
{

    /**
     * Selector for all available fields of Hrorg.
     * 
     */
    public final static HrorgSelectable ALL_FIELDS = new HrorgSelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>IUsrid</b></p>
     * 
     * @return
     *     Nome utente
     */
    @SerializedName("IUsrid")
    @JsonProperty("IUsrid")
    @Nullable
    @ODataField(odataName = "IUsrid")
    private String iUsrid;
    /**
     * Use with available fluent helpers to apply the <b>IUsrid</b> field to query operations.
     * 
     */
    public final static HrorgField<String> I_USRID = new HrorgField<String>("IUsrid");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Usrid</b></p>
     * 
     * @return
     *     ID sistema
     */
    @Key
    @SerializedName("Usrid")
    @JsonProperty("Usrid")
    @Nullable
    @ODataField(odataName = "Usrid")
    private String usrid;
    /**
     * Use with available fluent helpers to apply the <b>Usrid</b> field to query operations.
     * 
     */
    public final static HrorgField<String> USRID = new HrorgField<String>("Usrid");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Pernr</b></p>
     * 
     * @return
     *     C.I.D.
     */
    @SerializedName("Pernr")
    @JsonProperty("Pernr")
    @Nullable
    @ODataField(odataName = "Pernr")
    private String pernr;
    /**
     * Use with available fluent helpers to apply the <b>Pernr</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERNR = new HrorgField<String>("Pernr");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Stat2</b></p>
     * 
     * @return
     *     Occupazione
     */
    @SerializedName("Stat2")
    @JsonProperty("Stat2")
    @Nullable
    @ODataField(odataName = "Stat2")
    private String stat2;
    /**
     * Use with available fluent helpers to apply the <b>Stat2</b> field to query operations.
     * 
     */
    public final static HrorgField<String> STAT2 = new HrorgField<String>("Stat2");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @return
     *     Società
     */
    @SerializedName("Bukrs")
    @JsonProperty("Bukrs")
    @Nullable
    @ODataField(odataName = "Bukrs")
    private String bukrs;
    /**
     * Use with available fluent helpers to apply the <b>Bukrs</b> field to query operations.
     * 
     */
    public final static HrorgField<String> BUKRS = new HrorgField<String>("Bukrs");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Persa</b></p>
     * 
     * @return
     *     Area Personale
     */
    @SerializedName("Persa")
    @JsonProperty("Persa")
    @Nullable
    @ODataField(odataName = "Persa")
    private String persa;
    /**
     * Use with available fluent helpers to apply the <b>Persa</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERSA = new HrorgField<String>("Persa");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Btrtl</b></p>
     * 
     * @return
     *     Sottoarea Pers.
     */
    @SerializedName("Btrtl")
    @JsonProperty("Btrtl")
    @Nullable
    @ODataField(odataName = "Btrtl")
    private String btrtl;
    /**
     * Use with available fluent helpers to apply the <b>Btrtl</b> field to query operations.
     * 
     */
    public final static HrorgField<String> BTRTL = new HrorgField<String>("Btrtl");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Orgeh</b></p>
     * 
     * @return
     *     Unità org.
     */
    @SerializedName("Orgeh")
    @JsonProperty("Orgeh")
    @Nullable
    @ODataField(odataName = "Orgeh")
    private String orgeh;
    /**
     * Use with available fluent helpers to apply the <b>Orgeh</b> field to query operations.
     * 
     */
    public final static HrorgField<String> ORGEH = new HrorgField<String>("Orgeh");
    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Persg</b></p>
     * 
     * @return
     *     Status DIP
     */
    @SerializedName("Persg")
    @JsonProperty("Persg")
    @Nullable
    @ODataField(odataName = "Persg")
    private String persg;
    /**
     * Use with available fluent helpers to apply the <b>Persg</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERSG = new HrorgField<String>("Persg");
    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Persk</b></p>
     * 
     * @return
     *     Tipo DIP
     */
    @SerializedName("Persk")
    @JsonProperty("Persk")
    @Nullable
    @ODataField(odataName = "Persk")
    private String persk;
    /**
     * Use with available fluent helpers to apply the <b>Persk</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERSK = new HrorgField<String>("Persk");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Plans</b></p>
     * 
     * @return
     *     Posizione
     */
    @SerializedName("Plans")
    @JsonProperty("Plans")
    @Nullable
    @ODataField(odataName = "Plans")
    private String plans;
    /**
     * Use with available fluent helpers to apply the <b>Plans</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PLANS = new HrorgField<String>("Plans");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Stell</b></p>
     * 
     * @return
     *     Mansione
     */
    @SerializedName("Stell")
    @JsonProperty("Stell")
    @Nullable
    @ODataField(odataName = "Stell")
    private String stell;
    /**
     * Use with available fluent helpers to apply the <b>Stell</b> field to query operations.
     * 
     */
    public final static HrorgField<String> STELL = new HrorgField<String>("Stell");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Ename</b></p>
     * 
     * @return
     *     Nome dip./cand.
     */
    @SerializedName("Ename")
    @JsonProperty("Ename")
    @Nullable
    @ODataField(odataName = "Ename")
    private String ename;
    /**
     * Use with available fluent helpers to apply the <b>Ename</b> field to query operations.
     * 
     */
    public final static HrorgField<String> ENAME = new HrorgField<String>("Ename");
    /**
     * Constraints: Not nullable, Maximum length: 241 <p>Original property name from the Odata EDM: <b>Mail</b></p>
     * 
     * @return
     *     Lungh. ID/N.
     */
    @SerializedName("Mail")
    @JsonProperty("Mail")
    @Nullable
    @ODataField(odataName = "Mail")
    private String mail;
    /**
     * Use with available fluent helpers to apply the <b>Mail</b> field to query operations.
     * 
     */
    public final static HrorgField<String> MAIL = new HrorgField<String>("Mail");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Cenel</b></p>
     * 
     * @return
     *     Codice ENEL da 10
     */
    @SerializedName("Cenel")
    @JsonProperty("Cenel")
    @Nullable
    @ODataField(odataName = "Cenel")
    private String cenel;
    /**
     * Use with available fluent helpers to apply the <b>Cenel</b> field to query operations.
     * 
     */
    public final static HrorgField<String> CENEL = new HrorgField<String>("Cenel");
    /**
     * Constraints: Not nullable, Maximum length: 45 <p>Original property name from the Odata EDM: <b>Busline</b></p>
     * 
     * @return
     *     ID ogg. corr.
     */
    @SerializedName("Busline")
    @JsonProperty("Busline")
    @Nullable
    @ODataField(odataName = "Busline")
    private String busline;
    /**
     * Use with available fluent helpers to apply the <b>Busline</b> field to query operations.
     * 
     */
    public final static HrorgField<String> BUSLINE = new HrorgField<String>("Busline");
    /**
     * Constraints: Not nullable, Maximum length: 45 <p>Original property name from the Odata EDM: <b>Perimeter</b></p>
     * 
     * @return
     *     ID ogg. corr.
     */
    @SerializedName("Perimeter")
    @JsonProperty("Perimeter")
    @Nullable
    @ODataField(odataName = "Perimeter")
    private String perimeter;
    /**
     * Use with available fluent helpers to apply the <b>Perimeter</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERIMETER = new HrorgField<String>("Perimeter");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OrgehText</b></p>
     * 
     * @return
     *     Denominazione
     */
    @SerializedName("OrgehText")
    @JsonProperty("OrgehText")
    @Nullable
    @ODataField(odataName = "OrgehText")
    private String orgehText;
    /**
     * Use with available fluent helpers to apply the <b>OrgehText</b> field to query operations.
     * 
     */
    public final static HrorgField<String> ORGEH_TEXT = new HrorgField<String>("OrgehText");
    /**
     * Constraints: Not nullable, Maximum length: 15 <p>Original property name from the Odata EDM: <b>BtrtlDesc</b></p>
     * 
     * @return
     *     Testo SA Pers.
     */
    @SerializedName("BtrtlDesc")
    @JsonProperty("BtrtlDesc")
    @Nullable
    @ODataField(odataName = "BtrtlDesc")
    private String btrtlDesc;
    /**
     * Use with available fluent helpers to apply the <b>BtrtlDesc</b> field to query operations.
     * 
     */
    public final static HrorgField<String> BTRTL_DESC = new HrorgField<String>("BtrtlDesc");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>BuslineText</b></p>
     * 
     * @return
     *     Denominazione
     */
    @SerializedName("BuslineText")
    @JsonProperty("BuslineText")
    @Nullable
    @ODataField(odataName = "BuslineText")
    private String buslineText;
    /**
     * Use with available fluent helpers to apply the <b>BuslineText</b> field to query operations.
     * 
     */
    public final static HrorgField<String> BUSLINE_TEXT = new HrorgField<String>("BuslineText");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>PerimText</b></p>
     * 
     * @return
     *     Denominazione
     */
    @SerializedName("PerimText")
    @JsonProperty("PerimText")
    @Nullable
    @ODataField(odataName = "PerimText")
    private String perimText;
    /**
     * Use with available fluent helpers to apply the <b>PerimText</b> field to query operations.
     * 
     */
    public final static HrorgField<String> PERIM_TEXT = new HrorgField<String>("PerimText");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Dpersg</b></p>
     * 
     * @return
     *     Def. tipo DIP
     */
    @SerializedName("Dpersg")
    @JsonProperty("Dpersg")
    @Nullable
    @ODataField(odataName = "Dpersg")
    private String dpersg;
    /**
     * Use with available fluent helpers to apply the <b>Dpersg</b> field to query operations.
     * 
     */
    public final static HrorgField<String> DPERSG = new HrorgField<String>("Dpersg");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Dpersk</b></p>
     * 
     * @return
     *     Def. tipo DIP
     */
    @SerializedName("Dpersk")
    @JsonProperty("Dpersk")
    @Nullable
    @ODataField(odataName = "Dpersk")
    private String dpersk;
    /**
     * Use with available fluent helpers to apply the <b>Dpersk</b> field to query operations.
     * 
     */
    public final static HrorgField<String> DPERSK = new HrorgField<String>("Dpersk");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Dplans</b></p>
     * 
     * @return
     *     Denominazione
     */
    @SerializedName("Dplans")
    @JsonProperty("Dplans")
    @Nullable
    @ODataField(odataName = "Dplans")
    private String dplans;
    /**
     * Use with available fluent helpers to apply the <b>Dplans</b> field to query operations.
     * 
     */
    public final static HrorgField<String> DPLANS = new HrorgField<String>("Dplans");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Dstell</b></p>
     * 
     * @return
     *     Denominazione
     */
    @SerializedName("Dstell")
    @JsonProperty("Dstell")
    @Nullable
    @ODataField(odataName = "Dstell")
    private String dstell;
    /**
     * Use with available fluent helpers to apply the <b>Dstell</b> field to query operations.
     * 
     */
    public final static HrorgField<String> DSTELL = new HrorgField<String>("Dstell");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<Hrorg> getType() {
        return Hrorg.class;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>IUsrid</b></p>
     * 
     * @param iUsrid
     *     Nome utente
     */
    public void setIUsrid(
        @Nullable
        final String iUsrid) {
        rememberChangedField("IUsrid", this.iUsrid);
        this.iUsrid = iUsrid;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>Usrid</b></p>
     * 
     * @param usrid
     *     ID sistema
     */
    public void setUsrid(
        @Nullable
        final String usrid) {
        rememberChangedField("Usrid", this.usrid);
        this.usrid = usrid;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Pernr</b></p>
     * 
     * @param pernr
     *     C.I.D.
     */
    public void setPernr(
        @Nullable
        final String pernr) {
        rememberChangedField("Pernr", this.pernr);
        this.pernr = pernr;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Stat2</b></p>
     * 
     * @param stat2
     *     Occupazione
     */
    public void setStat2(
        @Nullable
        final String stat2) {
        rememberChangedField("Stat2", this.stat2);
        this.stat2 = stat2;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Bukrs</b></p>
     * 
     * @param bukrs
     *     Società
     */
    public void setBukrs(
        @Nullable
        final String bukrs) {
        rememberChangedField("Bukrs", this.bukrs);
        this.bukrs = bukrs;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Persa</b></p>
     * 
     * @param persa
     *     Area Personale
     */
    public void setPersa(
        @Nullable
        final String persa) {
        rememberChangedField("Persa", this.persa);
        this.persa = persa;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Btrtl</b></p>
     * 
     * @param btrtl
     *     Sottoarea Pers.
     */
    public void setBtrtl(
        @Nullable
        final String btrtl) {
        rememberChangedField("Btrtl", this.btrtl);
        this.btrtl = btrtl;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Orgeh</b></p>
     * 
     * @param orgeh
     *     Unità org.
     */
    public void setOrgeh(
        @Nullable
        final String orgeh) {
        rememberChangedField("Orgeh", this.orgeh);
        this.orgeh = orgeh;
    }

    /**
     * Constraints: Not nullable, Maximum length: 1 <p>Original property name from the Odata EDM: <b>Persg</b></p>
     * 
     * @param persg
     *     Status DIP
     */
    public void setPersg(
        @Nullable
        final String persg) {
        rememberChangedField("Persg", this.persg);
        this.persg = persg;
    }

    /**
     * Constraints: Not nullable, Maximum length: 2 <p>Original property name from the Odata EDM: <b>Persk</b></p>
     * 
     * @param persk
     *     Tipo DIP
     */
    public void setPersk(
        @Nullable
        final String persk) {
        rememberChangedField("Persk", this.persk);
        this.persk = persk;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Plans</b></p>
     * 
     * @param plans
     *     Posizione
     */
    public void setPlans(
        @Nullable
        final String plans) {
        rememberChangedField("Plans", this.plans);
        this.plans = plans;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>Stell</b></p>
     * 
     * @param stell
     *     Mansione
     */
    public void setStell(
        @Nullable
        final String stell) {
        rememberChangedField("Stell", this.stell);
        this.stell = stell;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Ename</b></p>
     * 
     * @param ename
     *     Nome dip./cand.
     */
    public void setEname(
        @Nullable
        final String ename) {
        rememberChangedField("Ename", this.ename);
        this.ename = ename;
    }

    /**
     * Constraints: Not nullable, Maximum length: 241 <p>Original property name from the Odata EDM: <b>Mail</b></p>
     * 
     * @param mail
     *     Lungh. ID/N.
     */
    public void setMail(
        @Nullable
        final String mail) {
        rememberChangedField("Mail", this.mail);
        this.mail = mail;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Cenel</b></p>
     * 
     * @param cenel
     *     Codice ENEL da 10
     */
    public void setCenel(
        @Nullable
        final String cenel) {
        rememberChangedField("Cenel", this.cenel);
        this.cenel = cenel;
    }

    /**
     * Constraints: Not nullable, Maximum length: 45 <p>Original property name from the Odata EDM: <b>Busline</b></p>
     * 
     * @param busline
     *     ID ogg. corr.
     */
    public void setBusline(
        @Nullable
        final String busline) {
        rememberChangedField("Busline", this.busline);
        this.busline = busline;
    }

    /**
     * Constraints: Not nullable, Maximum length: 45 <p>Original property name from the Odata EDM: <b>Perimeter</b></p>
     * 
     * @param perimeter
     *     ID ogg. corr.
     */
    public void setPerimeter(
        @Nullable
        final String perimeter) {
        rememberChangedField("Perimeter", this.perimeter);
        this.perimeter = perimeter;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OrgehText</b></p>
     * 
     * @param orgehText
     *     Denominazione
     */
    public void setOrgehText(
        @Nullable
        final String orgehText) {
        rememberChangedField("OrgehText", this.orgehText);
        this.orgehText = orgehText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 15 <p>Original property name from the Odata EDM: <b>BtrtlDesc</b></p>
     * 
     * @param btrtlDesc
     *     Testo SA Pers.
     */
    public void setBtrtlDesc(
        @Nullable
        final String btrtlDesc) {
        rememberChangedField("BtrtlDesc", this.btrtlDesc);
        this.btrtlDesc = btrtlDesc;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>BuslineText</b></p>
     * 
     * @param buslineText
     *     Denominazione
     */
    public void setBuslineText(
        @Nullable
        final String buslineText) {
        rememberChangedField("BuslineText", this.buslineText);
        this.buslineText = buslineText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>PerimText</b></p>
     * 
     * @param perimText
     *     Denominazione
     */
    public void setPerimText(
        @Nullable
        final String perimText) {
        rememberChangedField("PerimText", this.perimText);
        this.perimText = perimText;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Dpersg</b></p>
     * 
     * @param dpersg
     *     Def. tipo DIP
     */
    public void setDpersg(
        @Nullable
        final String dpersg) {
        rememberChangedField("Dpersg", this.dpersg);
        this.dpersg = dpersg;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>Dpersk</b></p>
     * 
     * @param dpersk
     *     Def. tipo DIP
     */
    public void setDpersk(
        @Nullable
        final String dpersk) {
        rememberChangedField("Dpersk", this.dpersk);
        this.dpersk = dpersk;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Dplans</b></p>
     * 
     * @param dplans
     *     Denominazione
     */
    public void setDplans(
        @Nullable
        final String dplans) {
        rememberChangedField("Dplans", this.dplans);
        this.dplans = dplans;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>Dstell</b></p>
     * 
     * @param dstell
     *     Denominazione
     */
    public void setDstell(
        @Nullable
        final String dstell) {
        rememberChangedField("Dstell", this.dstell);
        this.dstell = dstell;
    }

    @Override
    protected String getEntityCollection() {
        return "HrorgSet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("Usrid", getUsrid());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("IUsrid", getIUsrid());
        values.put("Usrid", getUsrid());
        values.put("Pernr", getPernr());
        values.put("Stat2", getStat2());
        values.put("Bukrs", getBukrs());
        values.put("Persa", getPersa());
        values.put("Btrtl", getBtrtl());
        values.put("Orgeh", getOrgeh());
        values.put("Persg", getPersg());
        values.put("Persk", getPersk());
        values.put("Plans", getPlans());
        values.put("Stell", getStell());
        values.put("Ename", getEname());
        values.put("Mail", getMail());
        values.put("Cenel", getCenel());
        values.put("Busline", getBusline());
        values.put("Perimeter", getPerimeter());
        values.put("OrgehText", getOrgehText());
        values.put("BtrtlDesc", getBtrtlDesc());
        values.put("BuslineText", getBuslineText());
        values.put("PerimText", getPerimText());
        values.put("Dpersg", getDpersg());
        values.put("Dpersk", getDpersk());
        values.put("Dplans", getDplans());
        values.put("Dstell", getDstell());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("IUsrid")) {
                final Object value = values.remove("IUsrid");
                if ((value == null)||(!value.equals(getIUsrid()))) {
                    setIUsrid(((String) value));
                }
            }
            if (values.containsKey("Usrid")) {
                final Object value = values.remove("Usrid");
                if ((value == null)||(!value.equals(getUsrid()))) {
                    setUsrid(((String) value));
                }
            }
            if (values.containsKey("Pernr")) {
                final Object value = values.remove("Pernr");
                if ((value == null)||(!value.equals(getPernr()))) {
                    setPernr(((String) value));
                }
            }
            if (values.containsKey("Stat2")) {
                final Object value = values.remove("Stat2");
                if ((value == null)||(!value.equals(getStat2()))) {
                    setStat2(((String) value));
                }
            }
            if (values.containsKey("Bukrs")) {
                final Object value = values.remove("Bukrs");
                if ((value == null)||(!value.equals(getBukrs()))) {
                    setBukrs(((String) value));
                }
            }
            if (values.containsKey("Persa")) {
                final Object value = values.remove("Persa");
                if ((value == null)||(!value.equals(getPersa()))) {
                    setPersa(((String) value));
                }
            }
            if (values.containsKey("Btrtl")) {
                final Object value = values.remove("Btrtl");
                if ((value == null)||(!value.equals(getBtrtl()))) {
                    setBtrtl(((String) value));
                }
            }
            if (values.containsKey("Orgeh")) {
                final Object value = values.remove("Orgeh");
                if ((value == null)||(!value.equals(getOrgeh()))) {
                    setOrgeh(((String) value));
                }
            }
            if (values.containsKey("Persg")) {
                final Object value = values.remove("Persg");
                if ((value == null)||(!value.equals(getPersg()))) {
                    setPersg(((String) value));
                }
            }
            if (values.containsKey("Persk")) {
                final Object value = values.remove("Persk");
                if ((value == null)||(!value.equals(getPersk()))) {
                    setPersk(((String) value));
                }
            }
            if (values.containsKey("Plans")) {
                final Object value = values.remove("Plans");
                if ((value == null)||(!value.equals(getPlans()))) {
                    setPlans(((String) value));
                }
            }
            if (values.containsKey("Stell")) {
                final Object value = values.remove("Stell");
                if ((value == null)||(!value.equals(getStell()))) {
                    setStell(((String) value));
                }
            }
            if (values.containsKey("Ename")) {
                final Object value = values.remove("Ename");
                if ((value == null)||(!value.equals(getEname()))) {
                    setEname(((String) value));
                }
            }
            if (values.containsKey("Mail")) {
                final Object value = values.remove("Mail");
                if ((value == null)||(!value.equals(getMail()))) {
                    setMail(((String) value));
                }
            }
            if (values.containsKey("Cenel")) {
                final Object value = values.remove("Cenel");
                if ((value == null)||(!value.equals(getCenel()))) {
                    setCenel(((String) value));
                }
            }
            if (values.containsKey("Busline")) {
                final Object value = values.remove("Busline");
                if ((value == null)||(!value.equals(getBusline()))) {
                    setBusline(((String) value));
                }
            }
            if (values.containsKey("Perimeter")) {
                final Object value = values.remove("Perimeter");
                if ((value == null)||(!value.equals(getPerimeter()))) {
                    setPerimeter(((String) value));
                }
            }
            if (values.containsKey("OrgehText")) {
                final Object value = values.remove("OrgehText");
                if ((value == null)||(!value.equals(getOrgehText()))) {
                    setOrgehText(((String) value));
                }
            }
            if (values.containsKey("BtrtlDesc")) {
                final Object value = values.remove("BtrtlDesc");
                if ((value == null)||(!value.equals(getBtrtlDesc()))) {
                    setBtrtlDesc(((String) value));
                }
            }
            if (values.containsKey("BuslineText")) {
                final Object value = values.remove("BuslineText");
                if ((value == null)||(!value.equals(getBuslineText()))) {
                    setBuslineText(((String) value));
                }
            }
            if (values.containsKey("PerimText")) {
                final Object value = values.remove("PerimText");
                if ((value == null)||(!value.equals(getPerimText()))) {
                    setPerimText(((String) value));
                }
            }
            if (values.containsKey("Dpersg")) {
                final Object value = values.remove("Dpersg");
                if ((value == null)||(!value.equals(getDpersg()))) {
                    setDpersg(((String) value));
                }
            }
            if (values.containsKey("Dpersk")) {
                final Object value = values.remove("Dpersk");
                if ((value == null)||(!value.equals(getDpersk()))) {
                    setDpersk(((String) value));
                }
            }
            if (values.containsKey("Dplans")) {
                final Object value = values.remove("Dplans");
                if ((value == null)||(!value.equals(getDplans()))) {
                    setDplans(((String) value));
                }
            }
            if (values.containsKey("Dstell")) {
                final Object value = values.remove("Dstell");
                if ((value == null)||(!value.equals(getDstell()))) {
                    setDstell(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >HrorgField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new HrorgField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >HrorgField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new HrorgField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public ErpConfigContext getErpConfigContext() {
        return super.getErpConfigContext();
    }

    /**
     * 
     * @deprecated
     *     Use {@link #attachToService(String, ErpConfigContext)} instead.
     */
    @Override
    @Deprecated
    public void setErpConfigContext(
        @Nullable
        final ErpConfigContext erpConfigContext) {
        super.setErpConfigContext(erpConfigContext);
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nullable
        final ErpConfigContext configContext) {
        super.attachToService(servicePath, configContext);
    }

    @Override
    protected String getDefaultServicePath() {
        return ZSCPAIDASRVService.DEFAULT_SERVICE_PATH;
    }

}
