/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv;

import java.util.Collections;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.s4hana.connectivity.ErpConfigContext;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import com.sap.cloud.sdk.s4hana.datamodel.odata.annotation.Key;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.VdmEntity;
import com.sap.cloud.sdk.typeconverter.TypeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import vdm.namespaces.zscpaidasrv.field.OdmField;
import vdm.namespaces.zscpaidasrv.selectable.OdmSelectable;
import vdm.services.ZSCPAIDASRVService;


/**
 * <p>Original entity name from the Odata EDM: <b>Odm</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class Odm
    extends VdmEntity<Odm>
{

    /**
     * Selector for all available fields of Odm.
     * 
     */
    public final static OdmSelectable ALL_FIELDS = new OdmSelectable() {


        @Nonnull
        @Override
        public String getFieldName() {
            return "*";
        }

        @Nonnull
        @Override
        public List<String> getSelections() {
            return Collections.singletonList("*");
        }

    }
    ;
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>InOrder</b></p>
     * 
     * @return
     *     Ordine
     */
    @Key
    @SerializedName("InOrder")
    @JsonProperty("InOrder")
    @Nullable
    @ODataField(odataName = "InOrder")
    private String inOrder;
    /**
     * Use with available fluent helpers to apply the <b>InOrder</b> field to query operations.
     * 
     */
    public final static OdmField<String> IN_ORDER = new OdmField<String>("InOrder");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OuOrderid</b></p>
     * 
     * @return
     *     Ordine
     */
    @Key
    @SerializedName("OuOrderid")
    @JsonProperty("OuOrderid")
    @Nullable
    @ODataField(odataName = "OuOrderid")
    private String ouOrderid;
    /**
     * Use with available fluent helpers to apply the <b>OuOrderid</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_ORDERID = new OdmField<String>("OuOrderid");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuOrderidD</b></p>
     * 
     * @return
     *     Tsto br.
     */
    @SerializedName("OuOrderidD")
    @JsonProperty("OuOrderidD")
    @Nullable
    @ODataField(odataName = "OuOrderidD")
    private String ouOrderidD;
    /**
     * Use with available fluent helpers to apply the <b>OuOrderidD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_ORDERID_D = new OdmField<String>("OuOrderidD");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSedeTecnica</b></p>
     * 
     * @return
     *     Sede tecnica
     */
    @SerializedName("OuSedeTecnica")
    @JsonProperty("OuSedeTecnica")
    @Nullable
    @ODataField(odataName = "OuSedeTecnica")
    private String ouSedeTecnica;
    /**
     * Use with available fluent helpers to apply the <b>OuSedeTecnica</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_SEDE_TECNICA = new OdmField<String>("OuSedeTecnica");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuSedeTecnicaD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuSedeTecnicaD")
    @JsonProperty("OuSedeTecnicaD")
    @Nullable
    @ODataField(odataName = "OuSedeTecnicaD")
    private String ouSedeTecnicaD;
    /**
     * Use with available fluent helpers to apply the <b>OuSedeTecnicaD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_SEDE_TECNICA_D = new OdmField<String>("OuSedeTecnicaD");
    /**
     * Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>OuEquipment</b></p>
     * 
     * @return
     *     Equipment
     */
    @SerializedName("OuEquipment")
    @JsonProperty("OuEquipment")
    @Nullable
    @ODataField(odataName = "OuEquipment")
    private String ouEquipment;
    /**
     * Use with available fluent helpers to apply the <b>OuEquipment</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_EQUIPMENT = new OdmField<String>("OuEquipment");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuEquipmentD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuEquipmentD")
    @JsonProperty("OuEquipmentD")
    @Nullable
    @ODataField(odataName = "OuEquipmentD")
    private String ouEquipmentD;
    /**
     * Use with available fluent helpers to apply the <b>OuEquipmentD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_EQUIPMENT_D = new OdmField<String>("OuEquipmentD");
    /**
     * Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>OuAssemblaggio</b></p>
     * 
     * @return
     *     Numero di serie
     */
    @SerializedName("OuAssemblaggio")
    @JsonProperty("OuAssemblaggio")
    @Nullable
    @ODataField(odataName = "OuAssemblaggio")
    private String ouAssemblaggio;
    /**
     * Use with available fluent helpers to apply the <b>OuAssemblaggio</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_ASSEMBLAGGIO = new OdmField<String>("OuAssemblaggio");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuAssemblaggioD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuAssemblaggioD")
    @JsonProperty("OuAssemblaggioD")
    @Nullable
    @ODataField(odataName = "OuAssemblaggioD")
    private String ouAssemblaggioD;
    /**
     * Use with available fluent helpers to apply the <b>OuAssemblaggioD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_ASSEMBLAGGIO_D = new OdmField<String>("OuAssemblaggioD");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OuSuperiorOrderid</b></p>
     * 
     * @return
     *     Ord. superiore
     */
    @SerializedName("OuSuperiorOrderid")
    @JsonProperty("OuSuperiorOrderid")
    @Nullable
    @ODataField(odataName = "OuSuperiorOrderid")
    private String ouSuperiorOrderid;
    /**
     * Use with available fluent helpers to apply the <b>OuSuperiorOrderid</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_SUPERIOR_ORDERID = new OdmField<String>("OuSuperiorOrderid");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>OuCft</b></p>
     * 
     * @return
     *     Ubicazione
     */
    @SerializedName("OuCft")
    @JsonProperty("OuCft")
    @Nullable
    @ODataField(odataName = "OuCft")
    private String ouCft;
    /**
     * Use with available fluent helpers to apply the <b>OuCft</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_CFT = new OdmField<String>("OuCft");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuCftD</b></p>
     * 
     * @return
     *     The ouCftD contained in this entity.
     */
    @SerializedName("OuCftD")
    @JsonProperty("OuCftD")
    @Nullable
    @ODataField(odataName = "OuCftD")
    private String ouCftD;
    /**
     * Use with available fluent helpers to apply the <b>OuCftD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_CFT_D = new OdmField<String>("OuCftD");
    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>OuRegione</b></p>
     * 
     * @return
     *     Sett. aziendale
     */
    @SerializedName("OuRegione")
    @JsonProperty("OuRegione")
    @Nullable
    @ODataField(odataName = "OuRegione")
    private String ouRegione;
    /**
     * Use with available fluent helpers to apply the <b>OuRegione</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_REGIONE = new OdmField<String>("OuRegione");
    /**
     * Constraints: Not nullable, Maximum length: 14 <p>Original property name from the Odata EDM: <b>OuRegioneD</b></p>
     * 
     * @return
     *     RespSettAz.
     */
    @SerializedName("OuRegioneD")
    @JsonProperty("OuRegioneD")
    @Nullable
    @ODataField(odataName = "OuRegioneD")
    private String ouRegioneD;
    /**
     * Use with available fluent helpers to apply the <b>OuRegioneD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_REGIONE_D = new OdmField<String>("OuRegioneD");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuTipologia</b></p>
     * 
     * @return
     *     Valore car.
     */
    @SerializedName("OuTipologia")
    @JsonProperty("OuTipologia")
    @Nullable
    @ODataField(odataName = "OuTipologia")
    private String ouTipologia;
    /**
     * Use with available fluent helpers to apply the <b>OuTipologia</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_TIPOLOGIA = new OdmField<String>("OuTipologia");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuTipologiaD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuTipologiaD")
    @JsonProperty("OuTipologiaD")
    @Nullable
    @ODataField(odataName = "OuTipologiaD")
    private String ouTipologiaD;
    /**
     * Use with available fluent helpers to apply the <b>OuTipologiaD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_TIPOLOGIA_D = new OdmField<String>("OuTipologiaD");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuParte</b></p>
     * 
     * @return
     *     Valore car.
     */
    @SerializedName("OuParte")
    @JsonProperty("OuParte")
    @Nullable
    @ODataField(odataName = "OuParte")
    private String ouParte;
    /**
     * Use with available fluent helpers to apply the <b>OuParte</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_PARTE = new OdmField<String>("OuParte");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuParteD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuParteD")
    @JsonProperty("OuParteD")
    @Nullable
    @ODataField(odataName = "OuParteD")
    private String ouParteD;
    /**
     * Use with available fluent helpers to apply the <b>OuParteD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_PARTE_D = new OdmField<String>("OuParteD");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSezione</b></p>
     * 
     * @return
     *     Valore car.
     */
    @SerializedName("OuSezione")
    @JsonProperty("OuSezione")
    @Nullable
    @ODataField(odataName = "OuSezione")
    private String ouSezione;
    /**
     * Use with available fluent helpers to apply the <b>OuSezione</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_SEZIONE = new OdmField<String>("OuSezione");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSezioneD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuSezioneD")
    @JsonProperty("OuSezioneD")
    @Nullable
    @ODataField(odataName = "OuSezioneD")
    private String ouSezioneD;
    /**
     * Use with available fluent helpers to apply the <b>OuSezioneD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_SEZIONE_D = new OdmField<String>("OuSezioneD");
    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>OuCdlResp</b></p>
     * 
     * @return
     *     Centro LavResp.
     */
    @SerializedName("OuCdlResp")
    @JsonProperty("OuCdlResp")
    @Nullable
    @ODataField(odataName = "OuCdlResp")
    private String ouCdlResp;
    /**
     * Use with available fluent helpers to apply the <b>OuCdlResp</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_CDL_RESP = new OdmField<String>("OuCdlResp");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuCdlRespD</b></p>
     * 
     * @return
     *     Definizione
     */
    @SerializedName("OuCdlRespD")
    @JsonProperty("OuCdlRespD")
    @Nullable
    @ODataField(odataName = "OuCdlRespD")
    private String ouCdlRespD;
    /**
     * Use with available fluent helpers to apply the <b>OuCdlRespD</b> field to query operations.
     * 
     */
    public final static OdmField<String> OU_CDL_RESP_D = new OdmField<String>("OuCdlRespD");
    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Operazione</b></p>
     * 
     * @return
     *     Operazione
     */
    @SerializedName("Operazione")
    @JsonProperty("Operazione")
    @Nullable
    @ODataField(odataName = "Operazione")
    private String operazione;
    /**
     * Use with available fluent helpers to apply the <b>Operazione</b> field to query operations.
     * 
     */
    public final static OdmField<String> OPERAZIONE = new OdmField<String>("Operazione");
    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>Attivita</b></p>
     * 
     * @return
     *     Ch.testo std
     */
    @SerializedName("Attivita")
    @JsonProperty("Attivita")
    @Nullable
    @ODataField(odataName = "Attivita")
    private String attivita;
    /**
     * Use with available fluent helpers to apply the <b>Attivita</b> field to query operations.
     * 
     */
    public final static OdmField<String> ATTIVITA = new OdmField<String>("Attivita");
    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>AttivitaD</b></p>
     * 
     * @return
     *     Oper. tsto br.
     */
    @SerializedName("AttivitaD")
    @JsonProperty("AttivitaD")
    @Nullable
    @ODataField(odataName = "AttivitaD")
    private String attivitaD;
    /**
     * Use with available fluent helpers to apply the <b>AttivitaD</b> field to query operations.
     * 
     */
    public final static OdmField<String> ATTIVITA_D = new OdmField<String>("AttivitaD");
    /**
     * Constraints: Not nullable, Maximum length: 9 <p>Original property name from the Odata EDM: <b>MatlGroup</b></p>
     * 
     * @return
     *     Gruppo merci
     */
    @SerializedName("MatlGroup")
    @JsonProperty("MatlGroup")
    @Nullable
    @ODataField(odataName = "MatlGroup")
    private String matlGroup;
    /**
     * Use with available fluent helpers to apply the <b>MatlGroup</b> field to query operations.
     * 
     */
    public final static OdmField<String> MATL_GROUP = new OdmField<String>("MatlGroup");
    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>MatlGroupD</b></p>
     * 
     * @return
     *     Def. gr. merci
     */
    @SerializedName("MatlGroupD")
    @JsonProperty("MatlGroupD")
    @Nullable
    @ODataField(odataName = "MatlGroupD")
    private String matlGroupD;
    /**
     * Use with available fluent helpers to apply the <b>MatlGroupD</b> field to query operations.
     * 
     */
    public final static OdmField<String> MATL_GROUP_D = new OdmField<String>("MatlGroupD");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Agreement</b></p>
     * 
     * @return
     *     Contratto
     */
    @SerializedName("Agreement")
    @JsonProperty("Agreement")
    @Nullable
    @ODataField(odataName = "Agreement")
    private String agreement;
    /**
     * Use with available fluent helpers to apply the <b>Agreement</b> field to query operations.
     * 
     */
    public final static OdmField<String> AGREEMENT = new OdmField<String>("Agreement");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>AgmtItem</b></p>
     * 
     * @return
     *     Pos. contratto
     */
    @SerializedName("AgmtItem")
    @JsonProperty("AgmtItem")
    @Nullable
    @ODataField(odataName = "AgmtItem")
    private String agmtItem;
    /**
     * Use with available fluent helpers to apply the <b>AgmtItem</b> field to query operations.
     * 
     */
    public final static OdmField<String> AGMT_ITEM = new OdmField<String>("AgmtItem");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ImpresaEsec</b></p>
     * 
     * @return
     *     Rifer. fornit.
     */
    @SerializedName("ImpresaEsec")
    @JsonProperty("ImpresaEsec")
    @Nullable
    @ODataField(odataName = "ImpresaEsec")
    private String impresaEsec;
    /**
     * Use with available fluent helpers to apply the <b>ImpresaEsec</b> field to query operations.
     * 
     */
    public final static OdmField<String> IMPRESA_ESEC = new OdmField<String>("ImpresaEsec");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>ImpresaEsecD</b></p>
     * 
     * @return
     *     Nome 1
     */
    @SerializedName("ImpresaEsecD")
    @JsonProperty("ImpresaEsecD")
    @Nullable
    @ODataField(odataName = "ImpresaEsecD")
    private String impresaEsecD;
    /**
     * Use with available fluent helpers to apply the <b>ImpresaEsecD</b> field to query operations.
     * 
     */
    public final static OdmField<String> IMPRESA_ESEC_D = new OdmField<String>("ImpresaEsecD");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ImpresaAf</b></p>
     * 
     * @return
     *     Fornitore
     */
    @SerializedName("ImpresaAf")
    @JsonProperty("ImpresaAf")
    @Nullable
    @ODataField(odataName = "ImpresaAf")
    private String impresaAf;
    /**
     * Use with available fluent helpers to apply the <b>ImpresaAf</b> field to query operations.
     * 
     */
    public final static OdmField<String> IMPRESA_AF = new OdmField<String>("ImpresaAf");
    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>ImpresaAfD</b></p>
     * 
     * @return
     *     Nome 2
     */
    @SerializedName("ImpresaAfD")
    @JsonProperty("ImpresaAfD")
    @Nullable
    @ODataField(odataName = "ImpresaAfD")
    private String impresaAfD;
    /**
     * Use with available fluent helpers to apply the <b>ImpresaAfD</b> field to query operations.
     * 
     */
    public final static OdmField<String> IMPRESA_AF_D = new OdmField<String>("ImpresaAfD");
    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Lcl</b></p>
     * 
     * @return
     *     LCL
     */
    @SerializedName("Lcl")
    @JsonProperty("Lcl")
    @Nullable
    @ODataField(odataName = "Lcl")
    private String lcl;
    /**
     * Use with available fluent helpers to apply the <b>Lcl</b> field to query operations.
     * 
     */
    public final static OdmField<String> LCL = new OdmField<String>("Lcl");
    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>LclItem</b></p>
     * 
     * @return
     *     Posizione
     */
    @SerializedName("LclItem")
    @JsonProperty("LclItem")
    @Nullable
    @ODataField(odataName = "LclItem")
    private String lclItem;
    /**
     * Use with available fluent helpers to apply the <b>LclItem</b> field to query operations.
     * 
     */
    public final static OdmField<String> LCL_ITEM = new OdmField<String>("LclItem");
    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OrderidTestata</b></p>
     * 
     * @return
     *     Ordine
     */
    @SerializedName("OrderidTestata")
    @JsonProperty("OrderidTestata")
    @Nullable
    @ODataField(odataName = "OrderidTestata")
    private String orderidTestata;
    /**
     * Use with available fluent helpers to apply the <b>OrderidTestata</b> field to query operations.
     * 
     */
    public final static OdmField<String> ORDERID_TESTATA = new OdmField<String>("OrderidTestata");

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<Odm> getType() {
        return Odm.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>InOrder</b></p>
     * 
     * @param inOrder
     *     Ordine
     */
    public void setInOrder(
        @Nullable
        final String inOrder) {
        rememberChangedField("InOrder", this.inOrder);
        this.inOrder = inOrder;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OuOrderid</b></p>
     * 
     * @param ouOrderid
     *     Ordine
     */
    public void setOuOrderid(
        @Nullable
        final String ouOrderid) {
        rememberChangedField("OuOrderid", this.ouOrderid);
        this.ouOrderid = ouOrderid;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuOrderidD</b></p>
     * 
     * @param ouOrderidD
     *     Tsto br.
     */
    public void setOuOrderidD(
        @Nullable
        final String ouOrderidD) {
        rememberChangedField("OuOrderidD", this.ouOrderidD);
        this.ouOrderidD = ouOrderidD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSedeTecnica</b></p>
     * 
     * @param ouSedeTecnica
     *     Sede tecnica
     */
    public void setOuSedeTecnica(
        @Nullable
        final String ouSedeTecnica) {
        rememberChangedField("OuSedeTecnica", this.ouSedeTecnica);
        this.ouSedeTecnica = ouSedeTecnica;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuSedeTecnicaD</b></p>
     * 
     * @param ouSedeTecnicaD
     *     Definizione
     */
    public void setOuSedeTecnicaD(
        @Nullable
        final String ouSedeTecnicaD) {
        rememberChangedField("OuSedeTecnicaD", this.ouSedeTecnicaD);
        this.ouSedeTecnicaD = ouSedeTecnicaD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>OuEquipment</b></p>
     * 
     * @param ouEquipment
     *     Equipment
     */
    public void setOuEquipment(
        @Nullable
        final String ouEquipment) {
        rememberChangedField("OuEquipment", this.ouEquipment);
        this.ouEquipment = ouEquipment;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuEquipmentD</b></p>
     * 
     * @param ouEquipmentD
     *     Definizione
     */
    public void setOuEquipmentD(
        @Nullable
        final String ouEquipmentD) {
        rememberChangedField("OuEquipmentD", this.ouEquipmentD);
        this.ouEquipmentD = ouEquipmentD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 18 <p>Original property name from the Odata EDM: <b>OuAssemblaggio</b></p>
     * 
     * @param ouAssemblaggio
     *     Numero di serie
     */
    public void setOuAssemblaggio(
        @Nullable
        final String ouAssemblaggio) {
        rememberChangedField("OuAssemblaggio", this.ouAssemblaggio);
        this.ouAssemblaggio = ouAssemblaggio;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuAssemblaggioD</b></p>
     * 
     * @param ouAssemblaggioD
     *     Definizione
     */
    public void setOuAssemblaggioD(
        @Nullable
        final String ouAssemblaggioD) {
        rememberChangedField("OuAssemblaggioD", this.ouAssemblaggioD);
        this.ouAssemblaggioD = ouAssemblaggioD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OuSuperiorOrderid</b></p>
     * 
     * @param ouSuperiorOrderid
     *     Ord. superiore
     */
    public void setOuSuperiorOrderid(
        @Nullable
        final String ouSuperiorOrderid) {
        rememberChangedField("OuSuperiorOrderid", this.ouSuperiorOrderid);
        this.ouSuperiorOrderid = ouSuperiorOrderid;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>OuCft</b></p>
     * 
     * @param ouCft
     *     Ubicazione
     */
    public void setOuCft(
        @Nullable
        final String ouCft) {
        rememberChangedField("OuCft", this.ouCft);
        this.ouCft = ouCft;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuCftD</b></p>
     * 
     * @param ouCftD
     *     The ouCftD to set.
     */
    public void setOuCftD(
        @Nullable
        final String ouCftD) {
        rememberChangedField("OuCftD", this.ouCftD);
        this.ouCftD = ouCftD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>OuRegione</b></p>
     * 
     * @param ouRegione
     *     Sett. aziendale
     */
    public void setOuRegione(
        @Nullable
        final String ouRegione) {
        rememberChangedField("OuRegione", this.ouRegione);
        this.ouRegione = ouRegione;
    }

    /**
     * Constraints: Not nullable, Maximum length: 14 <p>Original property name from the Odata EDM: <b>OuRegioneD</b></p>
     * 
     * @param ouRegioneD
     *     RespSettAz.
     */
    public void setOuRegioneD(
        @Nullable
        final String ouRegioneD) {
        rememberChangedField("OuRegioneD", this.ouRegioneD);
        this.ouRegioneD = ouRegioneD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuTipologia</b></p>
     * 
     * @param ouTipologia
     *     Valore car.
     */
    public void setOuTipologia(
        @Nullable
        final String ouTipologia) {
        rememberChangedField("OuTipologia", this.ouTipologia);
        this.ouTipologia = ouTipologia;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuTipologiaD</b></p>
     * 
     * @param ouTipologiaD
     *     Definizione
     */
    public void setOuTipologiaD(
        @Nullable
        final String ouTipologiaD) {
        rememberChangedField("OuTipologiaD", this.ouTipologiaD);
        this.ouTipologiaD = ouTipologiaD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuParte</b></p>
     * 
     * @param ouParte
     *     Valore car.
     */
    public void setOuParte(
        @Nullable
        final String ouParte) {
        rememberChangedField("OuParte", this.ouParte);
        this.ouParte = ouParte;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuParteD</b></p>
     * 
     * @param ouParteD
     *     Definizione
     */
    public void setOuParteD(
        @Nullable
        final String ouParteD) {
        rememberChangedField("OuParteD", this.ouParteD);
        this.ouParteD = ouParteD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSezione</b></p>
     * 
     * @param ouSezione
     *     Valore car.
     */
    public void setOuSezione(
        @Nullable
        final String ouSezione) {
        rememberChangedField("OuSezione", this.ouSezione);
        this.ouSezione = ouSezione;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>OuSezioneD</b></p>
     * 
     * @param ouSezioneD
     *     Definizione
     */
    public void setOuSezioneD(
        @Nullable
        final String ouSezioneD) {
        rememberChangedField("OuSezioneD", this.ouSezioneD);
        this.ouSezioneD = ouSezioneD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 8 <p>Original property name from the Odata EDM: <b>OuCdlResp</b></p>
     * 
     * @param ouCdlResp
     *     Centro LavResp.
     */
    public void setOuCdlResp(
        @Nullable
        final String ouCdlResp) {
        rememberChangedField("OuCdlResp", this.ouCdlResp);
        this.ouCdlResp = ouCdlResp;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>OuCdlRespD</b></p>
     * 
     * @param ouCdlRespD
     *     Definizione
     */
    public void setOuCdlRespD(
        @Nullable
        final String ouCdlRespD) {
        rememberChangedField("OuCdlRespD", this.ouCdlRespD);
        this.ouCdlRespD = ouCdlRespD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 4 <p>Original property name from the Odata EDM: <b>Operazione</b></p>
     * 
     * @param operazione
     *     Operazione
     */
    public void setOperazione(
        @Nullable
        final String operazione) {
        rememberChangedField("Operazione", this.operazione);
        this.operazione = operazione;
    }

    /**
     * Constraints: Not nullable, Maximum length: 7 <p>Original property name from the Odata EDM: <b>Attivita</b></p>
     * 
     * @param attivita
     *     Ch.testo std
     */
    public void setAttivita(
        @Nullable
        final String attivita) {
        rememberChangedField("Attivita", this.attivita);
        this.attivita = attivita;
    }

    /**
     * Constraints: Not nullable, Maximum length: 40 <p>Original property name from the Odata EDM: <b>AttivitaD</b></p>
     * 
     * @param attivitaD
     *     Oper. tsto br.
     */
    public void setAttivitaD(
        @Nullable
        final String attivitaD) {
        rememberChangedField("AttivitaD", this.attivitaD);
        this.attivitaD = attivitaD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 9 <p>Original property name from the Odata EDM: <b>MatlGroup</b></p>
     * 
     * @param matlGroup
     *     Gruppo merci
     */
    public void setMatlGroup(
        @Nullable
        final String matlGroup) {
        rememberChangedField("MatlGroup", this.matlGroup);
        this.matlGroup = matlGroup;
    }

    /**
     * Constraints: Not nullable, Maximum length: 20 <p>Original property name from the Odata EDM: <b>MatlGroupD</b></p>
     * 
     * @param matlGroupD
     *     Def. gr. merci
     */
    public void setMatlGroupD(
        @Nullable
        final String matlGroupD) {
        rememberChangedField("MatlGroupD", this.matlGroupD);
        this.matlGroupD = matlGroupD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Agreement</b></p>
     * 
     * @param agreement
     *     Contratto
     */
    public void setAgreement(
        @Nullable
        final String agreement) {
        rememberChangedField("Agreement", this.agreement);
        this.agreement = agreement;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>AgmtItem</b></p>
     * 
     * @param agmtItem
     *     Pos. contratto
     */
    public void setAgmtItem(
        @Nullable
        final String agmtItem) {
        rememberChangedField("AgmtItem", this.agmtItem);
        this.agmtItem = agmtItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ImpresaEsec</b></p>
     * 
     * @param impresaEsec
     *     Rifer. fornit.
     */
    public void setImpresaEsec(
        @Nullable
        final String impresaEsec) {
        rememberChangedField("ImpresaEsec", this.impresaEsec);
        this.impresaEsec = impresaEsec;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>ImpresaEsecD</b></p>
     * 
     * @param impresaEsecD
     *     Nome 1
     */
    public void setImpresaEsecD(
        @Nullable
        final String impresaEsecD) {
        rememberChangedField("ImpresaEsecD", this.impresaEsecD);
        this.impresaEsecD = impresaEsecD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ImpresaAf</b></p>
     * 
     * @param impresaAf
     *     Fornitore
     */
    public void setImpresaAf(
        @Nullable
        final String impresaAf) {
        rememberChangedField("ImpresaAf", this.impresaAf);
        this.impresaAf = impresaAf;
    }

    /**
     * Constraints: Not nullable, Maximum length: 30 <p>Original property name from the Odata EDM: <b>ImpresaAfD</b></p>
     * 
     * @param impresaAfD
     *     Nome 2
     */
    public void setImpresaAfD(
        @Nullable
        final String impresaAfD) {
        rememberChangedField("ImpresaAfD", this.impresaAfD);
        this.impresaAfD = impresaAfD;
    }

    /**
     * Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>Lcl</b></p>
     * 
     * @param lcl
     *     LCL
     */
    public void setLcl(
        @Nullable
        final String lcl) {
        rememberChangedField("Lcl", this.lcl);
        this.lcl = lcl;
    }

    /**
     * Constraints: Not nullable, Maximum length: 5 <p>Original property name from the Odata EDM: <b>LclItem</b></p>
     * 
     * @param lclItem
     *     Posizione
     */
    public void setLclItem(
        @Nullable
        final String lclItem) {
        rememberChangedField("LclItem", this.lclItem);
        this.lclItem = lclItem;
    }

    /**
     * Constraints: Not nullable, Maximum length: 12 <p>Original property name from the Odata EDM: <b>OrderidTestata</b></p>
     * 
     * @param orderidTestata
     *     Ordine
     */
    public void setOrderidTestata(
        @Nullable
        final String orderidTestata) {
        rememberChangedField("OrderidTestata", this.orderidTestata);
        this.orderidTestata = orderidTestata;
    }

    @Override
    protected String getEntityCollection() {
        return "OdmSet";
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        result.put("InOrder", getInOrder());
        result.put("OuOrderid", getOuOrderid());
        return result;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("InOrder", getInOrder());
        values.put("OuOrderid", getOuOrderid());
        values.put("OuOrderidD", getOuOrderidD());
        values.put("OuSedeTecnica", getOuSedeTecnica());
        values.put("OuSedeTecnicaD", getOuSedeTecnicaD());
        values.put("OuEquipment", getOuEquipment());
        values.put("OuEquipmentD", getOuEquipmentD());
        values.put("OuAssemblaggio", getOuAssemblaggio());
        values.put("OuAssemblaggioD", getOuAssemblaggioD());
        values.put("OuSuperiorOrderid", getOuSuperiorOrderid());
        values.put("OuCft", getOuCft());
        values.put("OuCftD", getOuCftD());
        values.put("OuRegione", getOuRegione());
        values.put("OuRegioneD", getOuRegioneD());
        values.put("OuTipologia", getOuTipologia());
        values.put("OuTipologiaD", getOuTipologiaD());
        values.put("OuParte", getOuParte());
        values.put("OuParteD", getOuParteD());
        values.put("OuSezione", getOuSezione());
        values.put("OuSezioneD", getOuSezioneD());
        values.put("OuCdlResp", getOuCdlResp());
        values.put("OuCdlRespD", getOuCdlRespD());
        values.put("Operazione", getOperazione());
        values.put("Attivita", getAttivita());
        values.put("AttivitaD", getAttivitaD());
        values.put("MatlGroup", getMatlGroup());
        values.put("MatlGroupD", getMatlGroupD());
        values.put("Agreement", getAgreement());
        values.put("AgmtItem", getAgmtItem());
        values.put("ImpresaEsec", getImpresaEsec());
        values.put("ImpresaEsecD", getImpresaEsecD());
        values.put("ImpresaAf", getImpresaAf());
        values.put("ImpresaAfD", getImpresaAfD());
        values.put("Lcl", getLcl());
        values.put("LclItem", getLclItem());
        values.put("OrderidTestata", getOrderidTestata());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("InOrder")) {
                final Object value = values.remove("InOrder");
                if ((value == null)||(!value.equals(getInOrder()))) {
                    setInOrder(((String) value));
                }
            }
            if (values.containsKey("OuOrderid")) {
                final Object value = values.remove("OuOrderid");
                if ((value == null)||(!value.equals(getOuOrderid()))) {
                    setOuOrderid(((String) value));
                }
            }
            if (values.containsKey("OuOrderidD")) {
                final Object value = values.remove("OuOrderidD");
                if ((value == null)||(!value.equals(getOuOrderidD()))) {
                    setOuOrderidD(((String) value));
                }
            }
            if (values.containsKey("OuSedeTecnica")) {
                final Object value = values.remove("OuSedeTecnica");
                if ((value == null)||(!value.equals(getOuSedeTecnica()))) {
                    setOuSedeTecnica(((String) value));
                }
            }
            if (values.containsKey("OuSedeTecnicaD")) {
                final Object value = values.remove("OuSedeTecnicaD");
                if ((value == null)||(!value.equals(getOuSedeTecnicaD()))) {
                    setOuSedeTecnicaD(((String) value));
                }
            }
            if (values.containsKey("OuEquipment")) {
                final Object value = values.remove("OuEquipment");
                if ((value == null)||(!value.equals(getOuEquipment()))) {
                    setOuEquipment(((String) value));
                }
            }
            if (values.containsKey("OuEquipmentD")) {
                final Object value = values.remove("OuEquipmentD");
                if ((value == null)||(!value.equals(getOuEquipmentD()))) {
                    setOuEquipmentD(((String) value));
                }
            }
            if (values.containsKey("OuAssemblaggio")) {
                final Object value = values.remove("OuAssemblaggio");
                if ((value == null)||(!value.equals(getOuAssemblaggio()))) {
                    setOuAssemblaggio(((String) value));
                }
            }
            if (values.containsKey("OuAssemblaggioD")) {
                final Object value = values.remove("OuAssemblaggioD");
                if ((value == null)||(!value.equals(getOuAssemblaggioD()))) {
                    setOuAssemblaggioD(((String) value));
                }
            }
            if (values.containsKey("OuSuperiorOrderid")) {
                final Object value = values.remove("OuSuperiorOrderid");
                if ((value == null)||(!value.equals(getOuSuperiorOrderid()))) {
                    setOuSuperiorOrderid(((String) value));
                }
            }
            if (values.containsKey("OuCft")) {
                final Object value = values.remove("OuCft");
                if ((value == null)||(!value.equals(getOuCft()))) {
                    setOuCft(((String) value));
                }
            }
            if (values.containsKey("OuCftD")) {
                final Object value = values.remove("OuCftD");
                if ((value == null)||(!value.equals(getOuCftD()))) {
                    setOuCftD(((String) value));
                }
            }
            if (values.containsKey("OuRegione")) {
                final Object value = values.remove("OuRegione");
                if ((value == null)||(!value.equals(getOuRegione()))) {
                    setOuRegione(((String) value));
                }
            }
            if (values.containsKey("OuRegioneD")) {
                final Object value = values.remove("OuRegioneD");
                if ((value == null)||(!value.equals(getOuRegioneD()))) {
                    setOuRegioneD(((String) value));
                }
            }
            if (values.containsKey("OuTipologia")) {
                final Object value = values.remove("OuTipologia");
                if ((value == null)||(!value.equals(getOuTipologia()))) {
                    setOuTipologia(((String) value));
                }
            }
            if (values.containsKey("OuTipologiaD")) {
                final Object value = values.remove("OuTipologiaD");
                if ((value == null)||(!value.equals(getOuTipologiaD()))) {
                    setOuTipologiaD(((String) value));
                }
            }
            if (values.containsKey("OuParte")) {
                final Object value = values.remove("OuParte");
                if ((value == null)||(!value.equals(getOuParte()))) {
                    setOuParte(((String) value));
                }
            }
            if (values.containsKey("OuParteD")) {
                final Object value = values.remove("OuParteD");
                if ((value == null)||(!value.equals(getOuParteD()))) {
                    setOuParteD(((String) value));
                }
            }
            if (values.containsKey("OuSezione")) {
                final Object value = values.remove("OuSezione");
                if ((value == null)||(!value.equals(getOuSezione()))) {
                    setOuSezione(((String) value));
                }
            }
            if (values.containsKey("OuSezioneD")) {
                final Object value = values.remove("OuSezioneD");
                if ((value == null)||(!value.equals(getOuSezioneD()))) {
                    setOuSezioneD(((String) value));
                }
            }
            if (values.containsKey("OuCdlResp")) {
                final Object value = values.remove("OuCdlResp");
                if ((value == null)||(!value.equals(getOuCdlResp()))) {
                    setOuCdlResp(((String) value));
                }
            }
            if (values.containsKey("OuCdlRespD")) {
                final Object value = values.remove("OuCdlRespD");
                if ((value == null)||(!value.equals(getOuCdlRespD()))) {
                    setOuCdlRespD(((String) value));
                }
            }
            if (values.containsKey("Operazione")) {
                final Object value = values.remove("Operazione");
                if ((value == null)||(!value.equals(getOperazione()))) {
                    setOperazione(((String) value));
                }
            }
            if (values.containsKey("Attivita")) {
                final Object value = values.remove("Attivita");
                if ((value == null)||(!value.equals(getAttivita()))) {
                    setAttivita(((String) value));
                }
            }
            if (values.containsKey("AttivitaD")) {
                final Object value = values.remove("AttivitaD");
                if ((value == null)||(!value.equals(getAttivitaD()))) {
                    setAttivitaD(((String) value));
                }
            }
            if (values.containsKey("MatlGroup")) {
                final Object value = values.remove("MatlGroup");
                if ((value == null)||(!value.equals(getMatlGroup()))) {
                    setMatlGroup(((String) value));
                }
            }
            if (values.containsKey("MatlGroupD")) {
                final Object value = values.remove("MatlGroupD");
                if ((value == null)||(!value.equals(getMatlGroupD()))) {
                    setMatlGroupD(((String) value));
                }
            }
            if (values.containsKey("Agreement")) {
                final Object value = values.remove("Agreement");
                if ((value == null)||(!value.equals(getAgreement()))) {
                    setAgreement(((String) value));
                }
            }
            if (values.containsKey("AgmtItem")) {
                final Object value = values.remove("AgmtItem");
                if ((value == null)||(!value.equals(getAgmtItem()))) {
                    setAgmtItem(((String) value));
                }
            }
            if (values.containsKey("ImpresaEsec")) {
                final Object value = values.remove("ImpresaEsec");
                if ((value == null)||(!value.equals(getImpresaEsec()))) {
                    setImpresaEsec(((String) value));
                }
            }
            if (values.containsKey("ImpresaEsecD")) {
                final Object value = values.remove("ImpresaEsecD");
                if ((value == null)||(!value.equals(getImpresaEsecD()))) {
                    setImpresaEsecD(((String) value));
                }
            }
            if (values.containsKey("ImpresaAf")) {
                final Object value = values.remove("ImpresaAf");
                if ((value == null)||(!value.equals(getImpresaAf()))) {
                    setImpresaAf(((String) value));
                }
            }
            if (values.containsKey("ImpresaAfD")) {
                final Object value = values.remove("ImpresaAfD");
                if ((value == null)||(!value.equals(getImpresaAfD()))) {
                    setImpresaAfD(((String) value));
                }
            }
            if (values.containsKey("Lcl")) {
                final Object value = values.remove("Lcl");
                if ((value == null)||(!value.equals(getLcl()))) {
                    setLcl(((String) value));
                }
            }
            if (values.containsKey("LclItem")) {
                final Object value = values.remove("LclItem");
                if ((value == null)||(!value.equals(getLclItem()))) {
                    setLclItem(((String) value));
                }
            }
            if (values.containsKey("OrderidTestata")) {
                final Object value = values.remove("OrderidTestata");
                if ((value == null)||(!value.equals(getOrderidTestata()))) {
                    setOrderidTestata(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param fieldType
     *     The Java type to use for the extension field when performing value comparisons.
     * @return
     *     A representation of an extension field from this entity.
     */
    @Nonnull
    public static<T >OdmField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final Class<T> fieldType) {
        return new OdmField<T>(fieldName);
    }

    /**
     * Use with available fluent helpers to apply an extension field to query operations.
     * 
     * @param typeConverter
     *     A TypeConverter<T, DomainT> instance whose first generic type matches the Java type of the field
     * @param fieldName
     *     The name of the extension field as returned by the OData service.
     * @param <T>
     *     The type of the extension field when performing value comparisons.
     * @param <DomainT>
     *     The type of the extension field as returned by the OData service.
     * @return
     *     A representation of an extension field from this entity, holding a reference to the given TypeConverter.
     */
    @Nonnull
    public static<T,DomainT >OdmField<T> field(
        @Nonnull
        final String fieldName,
        @Nonnull
        final TypeConverter<T, DomainT> typeConverter) {
        return new OdmField<T>(fieldName, typeConverter);
    }

    @Override
    @Nullable
    public ErpConfigContext getErpConfigContext() {
        return super.getErpConfigContext();
    }

    /**
     * 
     * @deprecated
     *     Use {@link #attachToService(String, ErpConfigContext)} instead.
     */
    @Override
    @Deprecated
    public void setErpConfigContext(
        @Nullable
        final ErpConfigContext erpConfigContext) {
        super.setErpConfigContext(erpConfigContext);
    }

    @Override
    protected void setServicePathForFetch(
        @Nullable
        final String servicePathForFetch) {
        super.setServicePathForFetch(servicePathForFetch);
    }

    @Override
    public void attachToService(
        @Nullable
        final String servicePath,
        @Nullable
        final ErpConfigContext configContext) {
        super.attachToService(servicePath, configContext);
    }

    @Override
    protected String getDefaultServicePath() {
        return ZSCPAIDASRVService.DEFAULT_SERVICE_PATH;
    }

}
