/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.FluentHelperByKey;
import vdm.namespaces.zscpaidasrv.selectable.OdmSelectable;


/**
 * Fluent helper to fetch a single {@link vdm.namespaces.zscpaidasrv.Odm Odm} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class OdmByKeyFluentHelper
    extends FluentHelperByKey<OdmByKeyFluentHelper, Odm, OdmSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link vdm.namespaces.zscpaidasrv.Odm Odm} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code Odm}
     * @param inOrder
     *     Ordine<p>Constraints: Not nullable, Maximum length: 12</p>
     * @param ouOrderid
     *     Ordine<p>Constraints: Not nullable, Maximum length: 12</p>
     */
    public OdmByKeyFluentHelper(
        @Nonnull
        final String servicePath, final String inOrder, final String ouOrderid) {
        super(servicePath);
        this.key.put("InOrder", inOrder);
        this.key.put("OuOrderid", ouOrderid);
    }

    @Override
    @Nonnull
    protected Class<Odm> getEntityClass() {
        return Odm.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
