/*
 * Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved.
 */

/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 2.19.0
 */

package vdm.namespaces.zscpaidasrv.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.s4hana.datamodel.odata.helper.batch.BatchFluentHelperBasic;
import vdm.services.ZSCPAIDASRVService;


/**
 * Default implementation of the {@link ZSCPAIDASRVServiceBatch} interface exposed in the {@link vdm.services.ZSCPAIDASRVService ZSCPAIDASRVService}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultZSCPAIDASRVServiceBatch
    extends BatchFluentHelperBasic<ZSCPAIDASRVServiceBatch, ZSCPAIDASRVServiceBatchChangeSet>
    implements ZSCPAIDASRVServiceBatch
{

    @Nonnull
    private final ZSCPAIDASRVService service;

    /**
     * Creates a new instance of this DefaultZSCPAIDASRVServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultZSCPAIDASRVServiceBatch(
        @Nonnull
        final ZSCPAIDASRVService service) {
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return ZSCPAIDASRVService.DEFAULT_SERVICE_PATH;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultZSCPAIDASRVServiceBatch getThis() {
        return this;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public ZSCPAIDASRVServiceBatchChangeSet beginChangeSet() {
        return new DefaultZSCPAIDASRVServiceBatchChangeSet(this, service);
    }

}
